/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2020-06-12 03:34:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class perSet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html style=\"height: auto;\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">\n");
      out.write("<title>所有文章</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/default/bootstrap/bootstrap.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"static/comp/fontawesome/css/font-awesome.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"static/comp/ionicons/css/ionicons.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"static/comp/adminlte/css/adminlte.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/default/mask.css\" />\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body style=\"height: auto;\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!--<div id=\"ORG_ADD_DIV_ID\" class=\"card card-info\" style=\"display:none\">  -->\n");
      out.write("\t<!-- <div id=\"POST_ADD_DIV_ID\" class=\"card card-info\">\n");
      out.write("\t\t<div class=\"card-header\">\n");
      out.write("\t\t\t<h3 class=\"card-title\">个人设置</h3>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<input id=\"oldUserName\" type=\"hidden\" value=\"\"> <input\n");
      out.write("\t\t\tid=\"regUUID\" type=\"hidden\" value=\"\" />\n");
      out.write("\t\t<div class=\"form-horizontal\">\n");
      out.write("\t\t\t<form name=\"PerForm\" action=\"/chinasofti/perSet/js/perSet.js\" onsubmit=\"return subReg()\" method=\"post\">\n");
      out.write("\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"JI_JOB_NAME\" class=\"col-sm-2 control-label\">用户名：</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<input value=\"\" type=\"text\" name=\"userName\" id=\"userName\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" style=\"width: 900px\" maxlength=\"16\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"JI_JOB_NAME\" class=\"col-sm-2 control-label\">性别：</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<select id=\"regSex\" name=\"regSex\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control highlight_green l35\" style=\"width: 900px\">\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"0\">男</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\">女</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"JI_JOB_NAME\" class=\"col-sm-2 control-label\">年龄：</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<select id=\"regAge\" name=\"regAge\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control highlight_green l35\" style=\"width: 900px\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"JI_JOB_NAME\" class=\"col-sm-2 control-label\">邮箱：</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<input value=\"\" type=\"text\" name=\"regEmial\" id=\"regEmial\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" style=\"width: 900px\" maxlength=\"16\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t/.card-body\n");
      out.write("\t\t\t\t\t<div class=\"card-footer col-md-3 col-md-offset-4\"\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 100%\" align=\"center\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-info\" onclick=\"subReg()\">提交</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"card-footer col-md-3 col-md-offset-4\" id=\"tishi\"\n");
      out.write("\t\t\t\t\t\tstyle=\"text-align: center; color: red; font-size: 15px\"></div>\n");
      out.write("\t\t\t\t\t/.card-footer\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t</div> -->\n");
      out.write("\t<div>\n");
      out.write("\t\t<h1>个人设置</h1>\n");
      out.write("\t\t\t<form action=\"perSetPost\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("\t\t\t\t用户名：<input type=\"text\" name=\"username\" id=\"username\" value=\"\" placeholder =\"更改用户名\"/>\n");
      out.write("\t\t\t\t<br/>\n");
      out.write("\t\t\t\t性别：<select id=\"regSex\" name=\"regSex\">\n");
      out.write("\t\t\t\t\t<option value=\"0\">男</option>\n");
      out.write("\t\t\t\t\t<option value=\"1\">女</option></select>\n");
      out.write("\t\t\t\t<!-- 性别：<input type=\"number\" name=\"userag\" id=\"userage\" value=\"\" placeholder =\"更改用户年龄\"/> -->\n");
      out.write("\t\t\t\t<br/>\n");
      out.write("\t\t\t\t年龄：<input type=\"number\" name=\"userage\" id=\"userage\" value=\"\" placeholder =\"更改用户年龄\"/>\n");
      out.write("\t\t\t\t<br/>\n");
      out.write("\t\t\t\t邮箱：<input type=\"text\" name=\"userEmail\" id=\"userEmail\" value=\"\" placeholder =\"更改邮箱\"/>\n");
      out.write("\t\t\t\t<br/>\n");
      out.write("\t\t\t\t<h2>请上传个人头像</h2>\n");
      out.write("\t\t\t\t<br/>\n");
      out.write("\t\t\t\t<input type=\"file\" name=\"file\"/>\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"提交\"/>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"static/comp/jquery/dist/jquery.js\"></script>\n");
      out.write("\t<script src=\"static/comp/jQuery-Storage-API/jquery.storageapi.js\"></script>\n");
      out.write("\t<script src=\"static/comp/jquery.form/jquery.form.min.js\"></script>\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"static/comp/jquery/plugins/scrollbar/perfect-scrollbar.jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"static/kindeditor/kindeditor-all.js\"\n");
      out.write("\t\ttype=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"static/kindeditor/kindeditor-all-min.js\"\n");
      out.write("\t\ttype=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"static/kindeditor/lang/zh-CN.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"static/js/common/mask.js\"></script>\n");
      out.write("\t<!-- 将该jsp与perSet.js文件关联 -->\n");
      out.write("\t<script src=\"chinasofti/perSet/js/perSet.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/alert.js\"></script>\n");
      out.write("\n");
      out.write("\t<!--  \n");
      out.write("\t\t<script src=\"/stmadc/stma/dc/include/js/jcommon.js\"></script>\n");
      out.write("\t\t\n");
      out.write("\t\t<script language=\"JavaScript\" src=\"/stmadc/jquery/jquery-ui-1.8.20.min.js\"></script>\n");
      out.write("\t\t<script src=\"/stmadc/static/comp/bootstrap/dist/js/bootstrap.js\"></script>\n");
      out.write("\t\t<script src=\"/stmadc/static/comp/adminlte/js/adminlte.min.js\"></script>\n");
      out.write("\t\t<script language=\"JavaScript\" src=\"/stmadc/stma/dc/include/js/jcommon.js\"></script>\n");
      out.write("\t-->\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
